export const skills = [
  'Git',
  'TypeScript',
  'JavaScript',
  'Kotlin',
  'Java',
  'Gradle',
  'Spring Boot',
  '[NPM] npm',
  '[NPM] pnpm',
  '[NPM] yarn',
  'React',
  'Next.js',
  'Remix',
  '[Docs] Fumadocs',
  '[Docs] Astro',
  'Vue',
  'Vite',
  'Webpack',
  '[UI] Boostrap',
  '[UI] Tailwind CSS',
  '[UI] daisyUI',
  '[UI] shadcn/ui',
  'Eslint',
  'Prettier',
  'Node',
  'Express',
  'Socket.IO',
  'Axios',
  '[ORM] Prisma',
  '[ORM] TypeORM',
  '[ORM] Sequelize',
  'HTML',
  'CSS',
  'discord.js',
  '[Minecraft] Bukkit, Spigot, Paper',
];
export default skills;
