import { Project, LocalProject } from '../types/Project.ts';

const response = await fetch('https://api.github.com/users/aculaOne/repos');
export const ghRepos: Project[] = await response.json();

export const lcRepos: LocalProject[] = [
  {
    id: 'farysd',
    name: 'FarySD',
    description:
      'FarySD [færi es di] - некоммерческий проект, созданный для улучшения коммуникативных навыков между участниками, где каждый откроет себя по-новому.',
    language: null,
    url: null,
    topics: ['Minecraft', 'Java', 'Kotlin'],
    images: ['preview/s/1', 'preview/s/2', 'preview/s/3'],
    subprojects: ['nelovy', 'farysd-site', 'farysd-bot'],
  },
  {
    id: 'farysd-bot',
    name: 'FarySD Bot',
    description: 'Бот для проекта FarySD',
    language: null,
    url: null,
    topics: ['Minecraft', 'Java', 'Kotlin'],
    sub: true,
  },
  {
    id: 'farysd-site',
    name: 'Сайт FarySD (V2)',
    description: 'Сайт проекта FarySD',
    language: null,
    url: null,
    topics: ['Web', 'Minecraft'],
    images: [
      'preview/lab',
      'preview/landing',
      'preview/profile/me',
      'preview/profile/_other',
      'preview/lenta',
      'preview/blog',
      'preview/forum',
    ],
    sub: true,
  },
  {
    id: 'nelovy',
    name: 'Nelovy',
    description: 'Сборка Minecraft сервера на ядре Paper',
    sub: true,
    language: null,
    topics: [],
    images: ['promo'],
    url: null,
  },
  {
    id: 'kristy',
    name: 'Kristy',
    description: 'Discord-бот, панель управления гильдией и другое',
    language: 'TypeScript',
    topics: ['Bot', 'Cute'],
    url: 'https://github.com/aculaOne/KristyType',
    subprojects: ['kristy-studio'],
  },
  {
    id: 'kristy-studio',
    name: 'KristyStudio',
    description: 'Панель управления гильдией',
    sub: true,
    language: null,
    topics: ['Bot', 'Design'],
    url: null,
    images: [
      'preview/0',
      'preview/1',
      'preview/General/Home',
      'preview/Profile/View',
      'preview/Profile/Settings',
      'preview/Profile/Settings-1',
    ],
  },
  {
    id: 'laf-info-site',
    name: 'LAF Site',
    description:
      'Цитата: "[LAF] – команда молодых, очень ленивых, но увлеченных работой энтузиастов, двигуящаяся к вершинам этого мира". Лицевая сторона сайта (Frontend) была создана полностью мной.',
    language: 'TypeScript',
    url: 'https://laf-info.netlify.app',
    topics: ['Web', 'React', 'Vite', 'Team'],
    images: ['preview/0', 'preview/1', 'preview/2', 'preview/404'],
  },
  {
    id: 'geva',
    name: 'Geva',
    description: 'Префикс для моих проектов',
    language: null,
    url: null,
    topics: [],
    subprojects: ['gevaui', 'geva-music'],
  },
  {
    id: 'mulink-os',
    name: 'Mulink OS',
    description: 'Имитация операционной системы под браузер (разработка отложена).',
    language: 'TypeScript',
    url: null,
    topics: ['Web', 'React'],
    images: [
      'preview/Main',
      'preview/Setup',
      'preview/Setup-1',
      'preview/Setup-2',
      'preview/Wekle',
      'preview/Wekle-1',
      'preview/Wekle-2',
      'preview/Phone',
      'preview/Phone-1',
      'preview/Phone-2',
      'preview/Phone-3',
    ],
  },
  // Эксперименты
  {
    id: 'experiments',
    name: 'Эксперименты',
    description: '',
    language: null,
    topics: [],
    url: null,
    subprojects: ['gevaui', 'ferisian-book'],
  },
  {
    id: 'gevaui',
    name: 'GevaUI',
    description: 'UI библиотека компонентов и стилей для TailwindCSS',
    sub: true,
    requirements: [
      'Современный дизайн',
      'Мягкость и элегантность (эксперимент)',
      'Лёгкость',
      'Грусть и воодушевление (эксперимент)',
      'В общем: сделать красиво и сочесть несочетаемое',
    ],
    language: null,
    url: null,
    topics: ['Web', 'React', 'Kit', 'UI', 'CSS'],
    images: ['preview'],
  },
  {
    id: 'geva-music',
    name: 'GevaMusic',
    description: 'Приложение для прослушивания музыки',
    sub: true,
    language: null,
    url: null,
    topics: ['Design'],
    images: ['preview/splash', 'preview/0', 'preview/1', 'preview/2'],
  },
  {
    id: 'ferisian-book',
    name: 'Ferisian Book',
    description:
      'Учебник был создан для реализации онлайн-справочника по ферийскому языку, а также обновлению и совершенствованию креативных навыков его создателя (меня).',
    sub: true,
    requirements: [
      'Использовать React',
      'Изучить фреймворк для создания документаций',
      'Мультиязычность',
      'Удобство',
    ],
    language: 'TypeScript',
    url: 'https://ferisian-book.netlify.app',
    topics: ['Web', 'React', 'Remix'],
    images: ['preview/0', 'preview/1', 'preview/2', 'preview/3'],
  },
  // Дизайн
  {
    id: 'design',
    name: 'Дизайн',
    description: '',
    language: null,
    topics: ['Design'],
    url: null,
    subprojects: ['gevaui', 'sefula-launcher', 'thevoid-site', 'lottop-info'],
  },
  {
    id: 'sefula-launcher',
    name: 'Sefula Launcher',
    description: 'Дизайн для игрового лаунчера (играючи)',
    sub: true,
    language: null,
    url: null,
    topics: ['Design'],
    images: ['preview/0', 'preview/1'],
  },
  {
    id: 'thevoid-site',
    name: 'Сайт The Void',
    description: 'Подарок в виде дизайна сайта моего коллеги',
    sub: true,
    language: null,
    topics: ['Design'],
    url: null,
    images: ['preview/0', 'preview/1'],
  },
  {
    id: 'lottop-info',
    name: 'Дизайн LotTop Info',
    description: 'Подарок в виде дизайна сайта моего знакомого',
    sub: true,
    language: null,
    topics: ['Design'],
    url: 'https://lottophello.github.io/lottop_info/',
    images: ['preview/0', 'preview/1'],
  },
];
